name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Run tests
      run: mvn -B test --file pom.xml
    - name: Prepare artifact for release
      run: |
        mkdir staging
        cp CPUEmulator/target/CPUEmulator-*-SNAPSHOT.jar staging/
        cp -r bin staging/
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: staging/

  release: 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-package

      - name: Zip Files
        run : zip -r CPUEmulator.zip .

      - name: Upload the final zip file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CPUEmulator.zip
          tag: release-${{ github.sha }}
          overwrite: true
          body: "Automatic release for version ${{ github.ref_name }}"
